// Generated by scripts/bundle-migrations.ts. Do not edit.
export type Migration = { version: string; sql: string };

export const migrations: Migration[] = [
  {
    version: "0000_init",
    sql: 'CREATE TABLE "folders" (\r\n\t"id" uuid PRIMARY KEY NOT NULL,\r\n\t"workspace_id" uuid DEFAULT \'00000000-0000-0000-0000-000000000001\' NOT NULL,\r\n\t"parent_id" uuid,\r\n\t"name" text NOT NULL,\r\n\t"created_at" timestamp with time zone DEFAULT now() NOT NULL,\r\n\t"updated_at" timestamp with time zone DEFAULT now() NOT NULL\r\n);\r\n--> statement-breakpoint\r\nCREATE TABLE "notes" (\r\n\t"id" uuid PRIMARY KEY NOT NULL,\r\n\t"workspace_id" uuid DEFAULT \'00000000-0000-0000-0000-000000000001\' NOT NULL,\r\n\t"folder_id" uuid,\r\n\t"title" text DEFAULT \'\' NOT NULL,\r\n\t"content" text DEFAULT \'\' NOT NULL,\r\n\t"archived_at" timestamp with time zone,\r\n\t"created_at" timestamp with time zone DEFAULT now() NOT NULL,\r\n\t"updated_at" timestamp with time zone DEFAULT now() NOT NULL\r\n);\r\n--> statement-breakpoint\r\nALTER TABLE "folders" ADD CONSTRAINT "folders_parent_id_folders_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."folders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\r\nALTER TABLE "notes" ADD CONSTRAINT "notes_folder_id_folders_id_fk" FOREIGN KEY ("folder_id") REFERENCES "public"."folders"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint\r\nCREATE INDEX "folders_parent_idx" ON "folders" USING btree ("parent_id");--> statement-breakpoint\r\nCREATE INDEX "notes_folder_idx" ON "notes" USING btree ("folder_id");--> statement-breakpoint\r\nCREATE INDEX "notes_updated_at_idx" ON "notes" USING btree ("updated_at");',
  },
  {
    version: "0001_embeddings",
    sql: 'CREATE TABLE "note_embeddings" (\r\n\t"note_id" uuid PRIMARY KEY NOT NULL,\r\n\t"model" text NOT NULL,\r\n\t"dimensions" integer NOT NULL,\r\n\t"values" real[] NOT NULL,\r\n\t"created_at" timestamp with time zone DEFAULT now() NOT NULL\r\n);\r\n--> statement-breakpoint\r\nALTER TABLE "note_embeddings" ADD CONSTRAINT "note_embeddings_note_id_notes_id_fk" FOREIGN KEY ("note_id") REFERENCES "public"."notes"("id") ON DELETE cascade ON UPDATE no action;',
  },
  {
    version: "0002_crazy_mantis",
    sql: 'CREATE TABLE "learning_events" (\n\t"id" uuid PRIMARY KEY NOT NULL,\n\t"workspace_id" uuid DEFAULT \'00000000-0000-0000-0000-000000000001\' NOT NULL,\n\t"type" text NOT NULL,\n\t"kind" text NOT NULL,\n\t"subject" text NOT NULL,\n\t"note_id" uuid,\n\t"created_at" timestamp with time zone DEFAULT now() NOT NULL\n);\n--> statement-breakpoint\nALTER TABLE "learning_events" ADD CONSTRAINT "learning_events_note_id_notes_id_fk" FOREIGN KEY ("note_id") REFERENCES "public"."notes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint\nCREATE INDEX "learning_events_subject_idx" ON "learning_events" USING btree ("kind","subject");--> statement-breakpoint\nCREATE INDEX "learning_events_created_at_idx" ON "learning_events" USING btree ("created_at");',
  },
];
