// Generated by scripts/bundle-migrations.ts. Do not edit.
export type Migration = { version: string; sql: string };

export const migrations: Migration[] = [
  {
    version: "0000_init",
    sql: 'CREATE TABLE "folders" (\n\t"id" uuid PRIMARY KEY NOT NULL,\n\t"workspace_id" uuid DEFAULT \'00000000-0000-0000-0000-000000000001\' NOT NULL,\n\t"parent_id" uuid,\n\t"name" text NOT NULL,\n\t"created_at" timestamp with time zone DEFAULT now() NOT NULL,\n\t"updated_at" timestamp with time zone DEFAULT now() NOT NULL\n);\n--> statement-breakpoint\nCREATE TABLE "notes" (\n\t"id" uuid PRIMARY KEY NOT NULL,\n\t"workspace_id" uuid DEFAULT \'00000000-0000-0000-0000-000000000001\' NOT NULL,\n\t"folder_id" uuid,\n\t"title" text DEFAULT \'\' NOT NULL,\n\t"content" text DEFAULT \'\' NOT NULL,\n\t"archived_at" timestamp with time zone,\n\t"created_at" timestamp with time zone DEFAULT now() NOT NULL,\n\t"updated_at" timestamp with time zone DEFAULT now() NOT NULL\n);\n--> statement-breakpoint\nALTER TABLE "folders" ADD CONSTRAINT "folders_parent_id_folders_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."folders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nALTER TABLE "notes" ADD CONSTRAINT "notes_folder_id_folders_id_fk" FOREIGN KEY ("folder_id") REFERENCES "public"."folders"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint\nCREATE INDEX "folders_parent_idx" ON "folders" USING btree ("parent_id");--> statement-breakpoint\nCREATE INDEX "notes_folder_idx" ON "notes" USING btree ("folder_id");--> statement-breakpoint\nCREATE INDEX "notes_updated_at_idx" ON "notes" USING btree ("updated_at");',
  },
  {
    version: "0001_embeddings",
    sql: 'CREATE TABLE "note_embeddings" (\n\t"note_id" uuid PRIMARY KEY NOT NULL,\n\t"model" text NOT NULL,\n\t"dimensions" integer NOT NULL,\n\t"values" real[] NOT NULL,\n\t"created_at" timestamp with time zone DEFAULT now() NOT NULL\n);\n--> statement-breakpoint\nALTER TABLE "note_embeddings" ADD CONSTRAINT "note_embeddings_note_id_notes_id_fk" FOREIGN KEY ("note_id") REFERENCES "public"."notes"("id") ON DELETE cascade ON UPDATE no action;',
  },
  {
    version: "0002_crazy_mantis",
    sql: 'CREATE TABLE "learning_events" (\n\t"id" uuid PRIMARY KEY NOT NULL,\n\t"workspace_id" uuid DEFAULT \'00000000-0000-0000-0000-000000000001\' NOT NULL,\n\t"type" text NOT NULL,\n\t"kind" text NOT NULL,\n\t"subject" text NOT NULL,\n\t"note_id" uuid,\n\t"created_at" timestamp with time zone DEFAULT now() NOT NULL\n);\n--> statement-breakpoint\nALTER TABLE "learning_events" ADD CONSTRAINT "learning_events_note_id_notes_id_fk" FOREIGN KEY ("note_id") REFERENCES "public"."notes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint\nCREATE INDEX "learning_events_subject_idx" ON "learning_events" USING btree ("kind","subject");--> statement-breakpoint\nCREATE INDEX "learning_events_created_at_idx" ON "learning_events" USING btree ("created_at");',
  },
  {
    version: "0003_equal_shen",
    sql: 'ALTER TABLE "notes" ADD COLUMN "search" "tsvector" GENERATED ALWAYS AS (setweight(to_tsvector(\'simple\', "notes"."title"), \'A\') || setweight(to_tsvector(\'simple\', "notes"."content"), \'B\')) STORED NOT NULL;--> statement-breakpoint\nCREATE INDEX "notes_search_idx" ON "notes" USING gin ("search");',
  },
  {
    version: "0004_daffy_warbound",
    sql: 'DROP TABLE "note_embeddings" CASCADE;',
  },
  {
    version: "0005_futuristic_meggan",
    sql: 'CREATE TABLE "note_vectors" (\n\t"note_id" uuid PRIMARY KEY NOT NULL,\n\t"model" text NOT NULL,\n\t"dimensions" integer NOT NULL,\n\t"values" "bytea" NOT NULL,\n\t"created_at" timestamp with time zone DEFAULT now() NOT NULL\n);\n--> statement-breakpoint\nALTER TABLE "note_vectors" ADD CONSTRAINT "note_vectors_note_id_notes_id_fk" FOREIGN KEY ("note_id") REFERENCES "public"."notes"("id") ON DELETE cascade ON UPDATE no action;',
  },
  {
    version: "0006_bitter_nuke",
    sql: 'CREATE TABLE "tasks" (\n\t"id" uuid PRIMARY KEY NOT NULL,\n\t"workspace_id" uuid DEFAULT \'00000000-0000-0000-0000-000000000001\' NOT NULL,\n\t"note_id" uuid NOT NULL,\n\t"title" text NOT NULL,\n\t"due_at" timestamp with time zone,\n\t"completed_at" timestamp with time zone,\n\t"created_at" timestamp with time zone DEFAULT now() NOT NULL,\n\t"updated_at" timestamp with time zone DEFAULT now() NOT NULL\n);\n--> statement-breakpoint\nALTER TABLE "tasks" ADD CONSTRAINT "tasks_note_id_notes_id_fk" FOREIGN KEY ("note_id") REFERENCES "public"."notes"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint\nCREATE INDEX "tasks_note_idx" ON "tasks" USING btree ("note_id");--> statement-breakpoint\nCREATE INDEX "tasks_due_at_idx" ON "tasks" USING btree ("due_at");',
  },
];
