/**
 * Inlines drizzle-kit's SQL output into a TypeScript module so migrations ship to the browser,
 * where there is no filesystem to read them from. Run through `bun run db:generate`.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const packageRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const migrationsDir = join(packageRoot, "drizzle");
const target = join(packageRoot, "src", "migrations.generated.ts");

const files = (await readdir(migrationsDir)).filter((file) => file.endsWith(".sql")).sort();

const entries = await Promise.all(
  files.map(async (file) => {
    const sql = await readFile(join(migrationsDir, file), "utf8");
    return `  {\n    version: ${JSON.stringify(file.replace(/\.sql$/, ""))},\n    sql: ${JSON.stringify(sql)},\n  },`;
  }),
);

await writeFile(
  target,
  `// Generated by scripts/bundle-migrations.ts. Do not edit.\n` +
    `export type Migration = { version: string; sql: string };\n\n` +
    `export const migrations: Migration[] = [\n${entries.join("\n")}\n];\n`,
);

console.log(`bundled ${files.length} migration(s) into src/migrations.generated.ts`);
